---
- name: enable multilib
  become: yes
  tags: update
  lineinfile:
    dest: /etc/pacman.conf
    backrefs: yes
    regexp: "^#[multilib]"
    line: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"

- name: upgrade system
  become: yes
  tags: update
  pacman: update_cache=yes upgrade=yes

- name: baseline packages
  become: yes
  pacman: name={{ item }} state=latest
  with_items:
  - bash-completion
  - git
  - gnupg
  - man-db
  - openssh
  - tree
  - wget
  - vim
  - zsh
  - zsh-completions

- name: set hostname
  become: yes
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
