#!/usr/bin/env bash

set -xeo pipefail

fail() {
  echo "$1" >&2 && exit 1
}

invoke() {
  if [[ "$(hostname)" == $1 ]]; then
    connection="-c local"
  fi
  ansible-playbook -i inventory --become --ask-become-pass ${connection} "$1.yml"
}

bootstrap() {
  [[ "$(id -u)" == 0 ]] || fail "This should be run as root"

  pacman -S --noconfirm ansible

  invoke bootstrap/tasks
  ansible-playbook -i inventory

  echo "Changing user password:"
  passwd "${user}"  # bit nasty
}

provision() {
  local machine=$1
  [[ -e "${machine}.yml" ]] || fail "Couldn't find machine: ${machine}"
  invoke "${machine}"
}

main() {
  cd "$(dirname "${BASH_SOURCE[0]}")"

  user=guy
  local machine=$1
  shift

  case ${machine} in
    --bootstrap)  bootstrap ;;
    *) 	          provision "${machine}" ;;
  esac
}

main "$@"
