#!/usr/bin/env bash

set -xeo pipefail

fail() {
  echo "$1" >&2 && exit 1
}

main() {
  cd "$(dirname "${BASH_SOURCE[0]}")"

  task=$1

  case $task in
    bootstrap)  bootstrap/run ;;
    *) 	        fail "Unknown task: ${task}" ;;
  esac
}

main "$@"
