---
- name: setup gpg
  shell: gpg --keyserver pgp.mit.edu --recv-keys {{ item }}
  with_items:
  - 702353E0F7E48EDB  # ncurses5-compat-libs developer
  
- name: setup vim
  include: vim.yml

- name: setup zsh
  include: zsh.yml

- name: setup SSH config
  template:
    src: ssh.config.j2
    dest: /home/{{ username }}/.ssh/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: tmux conf
  template:
    src: tmux.conf.j2
    dest: /home/{{ username }}/.tmux.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
 
- name: create symlinks
  file:
    path: "{{ item.link }}"
    src: "{{ item.target }}"
    state: link
  with_items:
  - link: "/home/{{ username }}/desktop"
    target: "/home/{{ username }}/Desktop"
  - link: "/home/{{ username }}/downloads"
    target: "/home/{{ username }}/Downloads"
