---
- name: create .vim
  file: path=/home/{{ username }}/.vim state=directory owner={{ username }} group={{ username }} mode=0755

- name: create bundle
  file: path=/home/{{ username }}/.vim/bundle state=directory owner={{ username }} group={{ username }} mode=0755

- name: create autoload
  file: path=/home/{{ username }}/.vim/autoload state=directory owner={{ username }} group={{ username }} mode=0755

- name: add vimrc
  template: src=vimrc.j2 dest=/home/{{ username }}/.vimrc owner={{ username }} group={{ username }} mode=0644

- name: install pathogen
  git:
    repo: ssh://git@github.com/tpope/vim-pathogen.git 
    dest: /home/{{ username }}/.vim/bundle/pathogen
    clone: yes
    update: yes
    accept_hostkey: yes
    key_file: /home/{{ username }}/.ssh/id_ecdsa

- name: symlink pathogen
  file:
    src: /home/{{ username }}/.vim/bundle/pathogen/autoload/pathogen.vim
    dest: /home/{{ username }}/.vim/autoload/pathogen.vim
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: install solarized
  git:
    repo: ssh://git@github.com/altercation/vim-colors-solarized.git
    dest: /home/{{ username }}/.vim/bundle/solarized
    clone: yes
    update: yes
    accept_hostkey: yes
    key_file: /home/{{ username }}/.ssh/id_ecdsa

- name: install plugins
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - vim-ctrlp
  - vim-nerdtree
  - vim-airline
  - ctags
  - cscope

- name: clone YCM
  git:
    repo: ssh://git@github.com/Valloric/YouCompleteMe.git
    dest: /home/{{ username }}/.vim/bundle/YouCompleteMe
    clone: yes
    update: yes
    accept_hostkey: yes
    key_file: /home/{{ username }}/.ssh/id_ecdsa
  register: ycm_updated

- name: install YCM
  shell: ./install.py --clang-completer
  chdir: /home/{{ username }}/.vim/bundle/YouCompleteMe
  when: ycm_updated
