---
- name: install packages
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - firefox
  - gimp

- name: install steam
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - steam
  - steam-native-runtime
