{
 "title": "Plants",
 "time": { "from": "now/w", "to": "now" },
 "panels": [
  {
   "title": "Moisture",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg_over_time(moisture{location=\"kitchen\", name=\"basil\"}[15m])",
     "legendFormat": "Basil"
    },
    {
     "expr": "100 - avg_over_time(moisture{location=\"kitchen\", name=\"parsley\"}[15m])",
     "legendFormat": "Parsley"
    },
    {
     "expr": "100 - avg_over_time(moisture{location=\"kitchen\", name=\"garlic\"}[15m])",
     "legendFormat": "Garlic"
    },
    {
     "expr": "100 - avg_over_time(moisture{location=\"kitchen\", name=\"raspberry\"}[15m])",
     "legendFormat": "Raspberry"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - moisture{name=\"light\"}",
     "legendFormat": "Lounge"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temperature{location=\"kitchen\"}",
     "legendFormat": "Kitchen"
    }
   ]
  },
  {
   "title": "Moisture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg_over_time(moisture{location=\"lounge\", name=\"yucca\"}[5m])",
     "legendFormat": "Yucca"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(humidity{location=\"kitchen\"}[5m])",
     "legendFormat": "Kitchen"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count_over_time(moisture{location=\"lounge\",name=\"yucca\"}[1m])"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count_over_time(moisture{location=\"kitchen\",name=\"garlic\"}[1m])"
    }
   ]
  }
 ]
}