---
- name: install generic tools
  pacman: name={{ item }} state=latest
  become: yes
  with_items:
  - base-devel
  - tig
  - afl
  - afl-utils
  - shellcheck
  
- name: install C/C++ toolchain
  pacman: name={{ item }} state=latest
  become: yes
  with_items:
  - gcc
  - clang
  - gdb
  - cgdb
  - cmake
  - make

- name: install python tools
  pacman: name={{ item }} state=latest
  become: yes
  with_items:
  - python
  - ipython
  - python-virtualenv
  - python-yaml
  - python-pip
  - python-pylint
  - python-pipenv
  - python-flake8

- name: install libraries
  pacman: name={{ item }} state=latest
  become: yes
  with_items:
  - allegro
