---
- name: install generic tools
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - tig
  - afl
  - afl-utils
  
- name: install C/C++ toolchain
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - gcc
  - clang
  - gdb
  - cgdb
  - cmake

- name: install python tools
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - python
  - ipython
  - python-virtualenv

- name: install libraries
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - allegro
