---
- name: copy pre-compiled binary
  become: yes
  copy: src=prometheus.armv8 dest=/usr/local/bin/prometheus owner=root group=root mode=0755

- name: copy prometheus config
  become: yes
  template: src=prometheus.yml.j2 dest=/etc/prometheus.yml owner=root group=root mode=0644

- name: copy systemd unit
  become: yes
  template: src=prometheus.service.j2 dest=/usr/lib/systemd/system/prometheus.service owner=root group=root mode=0644
  register: systemd_changed

- name: install nginx
  become: yes
  pacman: name=nginx state=installed

- name: copy nginx config
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  register: nginx_changed

- name: restart nginx service
  become: yes
  when: nginx_changed
  systemd: name=nginx state=restarted enabled=yes

- name: reload systemd
  become: yes
  when: systemd_changed
  shell: systemctl daemon-reload

- name: start prometheus service
  become: yes
  systemd: name=prometheus state=started enabled=yes

- name: restart prometheus service
  become: yes
  when: systemd_changed
  systemd: name=prometheus state=restarted

