---
- name: configure overlay
  become: yes
  lineinfile:
    line: "dtparam=i2c_arm=on"
    dest: /boot/config.txt

- name: install packages
  become: yes
  pacman:
    name: i2c-tools
    state: installed

- name: load kernel module
  become: yes
  template:
    src: modules-load.d-sensor.conf.j2
    dest: /etc/modules-load.d/sensor.conf
    owner: root
    mode: 0644

- name: sensor script
  become: yes
  template:
    src: sensor.py
    dest: /usr/local/bin/sensor
    owner: root
    group: root
    mode: 02755

- name: sensor systemd unit
  become: yes
  template:
    src: sensor.service.j2
    dest: /usr/lib/systemd/system/sensor.service
    owner: root
    group: root
    mode: 0644
  register: reload_systemd
    
- name: sensor systemd timer
  become: yes
  template:
    src: sensor.timer.j2
    dest: /usr/lib/systemd/system/sensor.timer
    owner: root
    group: root
    mode: 0644
  register: reload_systemd

- name: enable sensor unit
  become: yes
  systemd:
    name: sensor.timer
    enabled: yes
