---
- name: configure overlay
  become: yes
  lineinfile:
    line: "dtparam=i2c_arm=on"
    dest: /boot/config.txt

- name: install packages
  become: yes
  pacman: name={{ item }} state=installed
  with_items:
  - i2c-tools
  - nginx

- name: load kernel module
  become: yes
  template:
    src: modules-load.d-sensor.conf.j2
    dest: /etc/modules-load.d/sensor.conf
    owner: root
    mode: 0644

- name: sensor script
  become: yes
  copy:
    src: sensor.py
    dest: /usr/local/bin/sensor
    owner: root
    group: root
    mode: 0755

- name: sensor config
  become: yes
  template:
    src: "{{ hostname }}.txt"
    dest: /etc/sensor.conf
    owner: root
    group: root
    mode: 0644

- name: sensor data directory
  become: yes
  file:
    path: /var/run/sensor
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sensor systemd unit
  become: yes
  template:
    src: sensor.service.j2
    dest: /usr/lib/systemd/system/sensor.service
    owner: root
    group: root
    mode: 0644
  register: reload_systemd
    
- name: sensor systemd timer
  become: yes
  template:
    src: sensor.timer.j2
    dest: /usr/lib/systemd/system/sensor.timer
    owner: root
    group: root
    mode: 0644
  register: reload_systemd

- name: enable sensor unit
  become: yes
  systemd:
    name: sensor.timer
    enabled: yes

- name: configure nginx
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  register: nginx_changed

- name: start nginx
  become: yes
  when: nginx_changed
  systemd: name=nginx state=restarted enabled=yes
